# Generated by Django 3.2.8 on 2021-11-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_pk',
            new_name='movie',
        ),
    ]
